HttpMessage/Response
jasny/http-message pull request #10
Opened 2016-10-10 18:42 UTC by poratuk

2016-10-10 19:46 UTC, jasny requested changes
Just minor things

2016-10-10 19:46 UTC, jasny commented on src/Message/ProtocolVersion.php
> +        if ($version === '2.0') {
Instead of having to do `if ($version === '2.0')` we can do
`$version = number_format((float)$version, $version < 2 ? 1 : 0, '.', '');`

2016-10-10 19:46 UTC, jasny commented on src/Response/Body.php
> +    protected function appendToBody($string)
Why do we need this function?

2016-10-10 19:46 UTC, jasny commented on src/Response/Headers.php
> +        return array();
Use `[]` never `array()`

2016-10-10 19:46 UTC, jasny commented on src/Response/ProtocolVersion.php
> +        return "1.1";
Should be persistent. If response defaults to 1.1 than ServerRequest should do the same.

2016-10-10 19:46 UTC, jasny commented on src/Response/StatusCode.php
> +        return $this->code .' '.$this->phrase;
mind your spaces

2016-10-10 19:46 UTC, jasny commented on tests/ResponseTest.php
> + * @covers Jasny\HttpMessage\Response\Body
Also add `@covers` for `Jasny\HttpMessage\Message` traits.

2016-10-10 19:48 UTC, jasny commented on tests/ResponseTest.php
> + * @covers Jasny\HttpMessage\Response\Body
`ServerRequestTest` should also have `@covers` for `Message` traits

2016-10-11 06:22 UTC, poratuk commented on src/Response/Body.php
> +    protected function appendToBody($string)
Sorry.
Must be a public function to give user ability append to already created body some string (like ability print <header>, then append header, left side, main content... etc.)

2016-10-11 06:26 UTC, poratuk commented on src/Response/ProtocolVersion.php
> +        return "1.1";
Changed in the Server request to 1.1, because this is more popular in this time and many programs need to be work server on protocol 1.1

2016-10-11 14:04 UTC, jasny approved these changes

2016-10-11 14:05 UTC, merged