Response headers class
jasny/http-message pull request #14
Opened 2016-10-18 10:44 UTC by poratuk

2016-10-19 19:34 UTC, jasny requested changes

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +     * @response Header class object
`@response`?? no

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +    public function __construct($incomingArray = [])
The constructor shouldn't take any arguments. Just creating a `ResposneHeaders` object, shouldn't change the global state.

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +    protected $isStale;
Should be only `true` or `false`

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +    protected function assertStale()
Function should be named `assertNotStale` since that's what's you're asserting.

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +    protected function setClassStale()
Rename to `turnStale`, so it's the same as in [`ServerRequest\GlobalEnvironment`](https://github.com/jasny/http-message/blob/master/src/ServerRequest/GlobalEnvironment.php#L95).

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +     * echo $name . ': ' . implode(', ', $values);
Do correct indenting, also in comments

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +        }
This code is duplicated (twice). Instead add `protected function getRawHeader()`, that returns the header value.

2016-10-19 19:34 UTC, jasny commented on src/ResponseHeaders.php
> +
Also add an `isStale` method. This will help in the tests.

2016-10-19 19:34 UTC, jasny commented on tests/ResponseHeadersTest.php
> +        $this->assertNotSame($this->headers, $header);
Test that `$this->headers` is stale.

2016-10-19 19:34 UTC, jasny commented on tests/ResponseHeadersTest.php
> + * @runTestsInSeparateProcesses
Don't run tests in separate process.

2016-10-19 19:34 UTC, jasny commented on tests/ResponseHeadersTest.php
> +
Unset `$_GLOBALS['headersList']` and `$_GLOBALS['responseCode']` after each test.

2016-10-20 13:37 UTC, poratuk commented on tests/ResponseHeadersTest.php
> +
https://phpunit.de/manual/current/en/fixtures.html#fixtures.more-setup-than-teardown
By default, PHPUnit runs your tests in a way where changes to global and super-global variables ($GLOBALS, $_ENV, $_POST, $_GET, $_COOKIE, $_SERVER, $_FILES, $_REQUEST) do not affect other tests. Optionally, this isolation can be extended to static attributes of classes.

2016-11-03 21:21 UTC, merged